---
title: "10-subgroup-correlations"
output: html_document
---

# Load relevant packages
```{r}
library(tidyverse)
library(ggcorrplot)
```

# Read in all files
```{r}
file_names = list.files(path = "./subdata/", pattern = "*.csv", full.names = T)
df_names = vector()
for (i in file_names) {
  curr_df = str_match(i, "subdata/*(.*?).csv")[,2]
  df_names = c(df_names, curr_df)
  df_output = read_csv(i)[,-1] %>% column_to_rownames(., var = "patient_id")
  df_output = df_output[,colSums(is.na(df_output))<nrow(df_output)]
  assign(curr_df, df_output)
}
```

# Correlograms

* Correlations done via pairwise complete observations, NA correlations coerced to zero.
* new_data and blood_test subgroups done separately due to large number of variables
* urine done separately because mostly character variables
```{r}
for (i in df_names[-c(4, 5, 8)]) {
  corr_df = get(i)
  names(corr_df) = str_sub(names(corr_df), 1, 15)
  current_cor = round(cor(corr_df, use = "pairwise.complete.obs"), 1)
  current_cor[is.na(current_cor)] = 0
  print(ggcorrplot(current_cor, hc.order = TRUE,
             type = "lower",
             lab = TRUE,
             lab_size = 2,
             method="circle",
             colors = c("tomato2", "white", "springgreen3"),
             title=paste("Correlogram of", i),
             ggtheme=theme_bw))
}
```

# Urine Subgroup
```{r}
urine_cor = cor(urine_subgroup[,c(1,2,6,9)], use = "pairwise.complete.obs") %>% as.data.frame()
urine_cor
```

# New Data
```{r}
new_data_cor = cor(new_data, use = "pairwise.complete.obs")

for (i in 1:ncol(new_data_cor)) {
  relevant_cor = new_data_cor[,i][abs(new_data_cor[,i])>.5]
  relevant_cor = relevant_cor[!is.na(relevant_cor)]
  current_cor = data.frame(relevant_cor[names(relevant_cor) != colnames(new_data_cor)[i]])
  names(current_cor) = colnames(new_data_cor)[i]
  if(nrow(current_cor)>0) {print(current_cor)}
}
```

# Blood Test
```{r}
blood_test_cor = cor(blood_test_subgroup, use = "pairwise.complete.obs")

for (i in 1:ncol(blood_test_cor)) {
  relevant_cor = blood_test_cor[,i][abs(blood_test_cor[,i])>.5]
  relevant_cor = relevant_cor[!is.na(relevant_cor)]
  current_cor = data.frame(relevant_cor[names(relevant_cor) != colnames(blood_test_cor)[i]])
  names(current_cor) = colnames(blood_test_cor)[i]
  if(nrow(current_cor)>0) {print(current_cor)}
}
```
